#!/usr/bin/env bash
# This script displays "To infinity and beyind" and
# traps SIGTERM

i=1

while [ $i -eq 1 ]
do
    trap "echo I am invincible!!!" TERM
    echo "To infinity and behind"
    sleep 2
done
