#!/usr/bin/env bash
# This script implements Fizz Buzz Algorithm

for i in {1..100}
do
    if [ $(($i % 3)) == 0 ] && [ $(($i % 5)) == 0 ]
    then
	echo "FizzBuzz"

    elif [ $(expr $i % 5) -eq 0 ]
    then
	echo "Buzz"

    elif [ $(($i % 3)) == 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
