#!/usr/bin/env bash
# This scripts displays "Best School" 9 times and "Hi" 1 time

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi

    (( i++ ))

done
