#!/usr/bin/env bash
# This script checks for school file and
# prints different statements according to school state

file=school

if [ -e $file ]
then
    echo "$file file exists"
    if [ -s $file ]
    then
	echo "$file is not empty"
    else
	echo "$file is empty"
    fi
    if [ -f $file ]
    then
	echo "$file is a regular file"
    fi
else
    echo "$file does not exist"
fi
